# Site settings
title: Lorem Ipsum - Web Developer
description: "A blog about lorem ipsum ..."
baseurl: "/space-jekyll-template" # for test: remove string '/space-jekyll-template' to ''
url: "http://victorvoid.github.io/space-jekyll-template/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: lorem ipsum
user_title: Lorem Ipsum - FrontEnd
email: lorem.lorem@ipsum.com
twitter_username: loremipsum
github_username:  loremipsum
discord_invite: cj5rg # Example: Discord server invite gg extension like in 'https://discord.gg/cj5rg'
linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: loremipsum
profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png

<<<<<<< HEAD
# Build settings
=======
# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "myskin" # "default"  "air", "aqua", "contrast", , "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR" # 블로그 사용 언어
title                    : "닝닝 아니고 닌닌" # 블로그 타이틀
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "닌닌"
description              : "소소한 기"
url                      : "https://ae-ziho.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "유저이름/comments" #댓글 경로 / github name/repository
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/logo.png" # 타이틀 옆 로고
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # true, false (default)
words_per_minute         : 200

comments: # 블로그 댓글 활용
  provider               : "utterances" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : #"유저이름-github-io" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : "github-light" # "github-light" (default), "github-dark"
    issue_term           : "pathname" # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : false # true, false (default)
search_full_content      : false # true, false (default)
search_provider          : #lunr # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
  
  
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing

# instagram : 0ldcar_  
# email : chh96077@gmail.com
# github : heoni00

twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
  
  
og_image                 :  "/assets/images/dol_kakao.jpg" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics: # 블로그 접근 경로 확인 코드 
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-169251732-1"
    anonymize_ip         : false # true, false (default)


# Site Author / 사이드바 소개 부분
author:
  name             : "닉네임"
  avatar           : "/assets/images/profile.jpg"
  bio              : "간단한 글귀"
  location         : "사는 지역"
  
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:이메일주소@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/유저이름"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/인스타 아이디"
    #- label: "Website"
    #  icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    #- label: "Facebook"
    #  icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/유저이름"
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
      # url:
    #- label: "Facebook"
    #  icon: "fab fa-fw fa-facebook-square"
      # url:
    #- label: "GitLab"
    #  icon: "fab fa-fw fa-gitlab"
      # url:
    #- label: "Bitbucket"
    #  icon: "fab fa-fw fa-bitbucket"
      # url:
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
      # url:


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
>>>>>>> 58002d80ac77ecd1d06210f45c7026a7e44ab4d8
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/victorvoid
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/victorvoid
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

<<<<<<< HEAD
# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
=======
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
      sidebar_main: true
>>>>>>> 58002d80ac77ecd1d06210f45c7026a7e44ab4d8
